//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perSONA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selecione uma pasta e salve a alteração")]
        public string RESULTS_FOLDER {
            get {
                return ((string)(this["RESULTS_FOLDER"]));
            }
            set {
                this["RESULTS_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PTMGF-28VKB-2W934-482QH-98623")]
        public string SERIAL_KEY {
            get {
                return ((string)(this["SERIAL_KEY"]));
            }
            set {
                this["SERIAL_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DEMO_VERSION {
            get {
                return ((bool)(this["DEMO_VERSION"]));
            }
            set {
                this["DEMO_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2019-10-07")]
        public global::System.DateTime FIRST_USE_DATA {
            get {
                return ((global::System.DateTime)(this["FIRST_USE_DATA"]));
            }
            set {
                this["FIRST_USE_DATA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FIRST_USE {
            get {
                return ((bool)(this["FIRST_USE"]));
            }
            set {
                this["FIRST_USE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CALIBRATION_MODE {
            get {
                return ((string)(this["CALIBRATION_MODE"]));
            }
            set {
                this["CALIBRATION_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REPRODUCTION_MODE {
            get {
                return ((string)(this["REPRODUCTION_MODE"]));
            }
            set {
                this["REPRODUCTION_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CALIBRATION_ID {
            get {
                return ((int)(this["CALIBRATION_ID"]));
            }
            set {
                this["CALIBRATION_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ITERATOR {
            get {
                return ((int)(this["ITERATOR"]));
            }
            set {
                this["ITERATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int SPEAKER_VOLUME {
            get {
                return ((int)(this["SPEAKER_VOLUME"]));
            }
            set {
                this["SPEAKER_VOLUME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int EARPHONE_VOLUME {
            get {
                return ((int)(this["EARPHONE_VOLUME"]));
            }
            set {
                this["EARPHONE_VOLUME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data/Equipments.xlsx")]
        public string EQUIPMENTS_TABLE_LOCATION {
            get {
                return ((string)(this["EQUIPMENTS_TABLE_LOCATION"]));
            }
            set {
                this["EQUIPMENTS_TABLE_LOCATION"] = value;
            }
        }
    }
}
